# SwiftLint Configuration for iOS/macOS Planner App

# Включенные директории
included:
  - IWBB
  - Shared
  - Tests

# Исключенные директории
excluded:
  - Pods
  - .build
  - DerivedData
  - Package.swift
  - fastlane
  - Configurations

# Отключенные правила (слишком строгие для SwiftUI)
disabled_rules:
  - line_length # SwiftUI может иметь длинные строки
  - function_body_length # SwiftUI body может быть длинным
  - file_length # SwiftUI Views могут быть большими
  - type_body_length # SwiftUI Views типы могут быть большими
  - trailing_whitespace # Автоформатирование решает это

# Включенные дополнительные правила
opt_in_rules:
  - array_init
  - attributes
  - closure_end_indentation
  - closure_spacing
  - collection_alignment
  - contains_over_filter_count
  - contains_over_filter_is_empty
  - contains_over_first_not_nil
  - convenience_type
  - discouraged_object_literal
  - empty_collection_literal
  - empty_count
  - empty_string
  - enum_case_associated_values_count
  - explicit_init
  - extension_access_modifier
  - fallthrough
  - fatal_error_message
  - first_where
  - flatmap_over_map_reduce
  - force_unwrapping
  - implicit_return
  - joined_default_parameter
  - last_where
  - legacy_random
  - literal_expression_end_indentation
  - lower_acl_than_parent
  - modifier_order
  - multiline_arguments
  - multiline_function_chains
  - multiline_literal_brackets
  - multiline_parameters
  - nimble_operator
  - nslocalizedstring_key
  - number_separator
  - object_literal
  - operator_usage_whitespace
  - overridden_super_call
  - override_in_extension
  - pattern_matching_keywords
  - prefer_self_type_over_type_of_self
  - prefer_zero_over_explicit_init
  - prefixed_toplevel_constant
  - prohibited_super_call
  - quick_discouraged_call
  - quick_discouraged_focused_test
  - quick_discouraged_pending_test
  - reduce_into
  - redundant_nil_coalescing
  - redundant_type_annotation
  - single_test_class
  - sorted_first_last
  - sorted_imports
  - static_operator
  - strong_iboutlet
  - toggle_bool
  - trailing_closure
  - unneeded_parentheses_in_closure_argument
  - unowned_variable_capture
  - untyped_error_in_catch
  - vertical_parameter_alignment_on_call
  - vertical_whitespace_closing_braces
  - vertical_whitespace_opening_braces
  - xct_specific_matcher
  - yoda_condition

# Кастомные настройки правил
function_parameter_count:
  warning: 6
  error: 8

identifier_name:
  min_length: 1 # Разрешаем короткие имена как 'id'
  max_length: 50
  excluded:
    - id
    - db
    - i
    - j
    - x
    - y
    - z

type_name:
  min_length: 3
  max_length: 40
  excluded:
    - ID
    - URL
    - UUID

large_tuple:
  warning: 3
  error: 4

nesting:
  type_level:
    warning: 2
    error: 3
  function_level:
    warning: 3
    error: 5

cyclomatic_complexity:
  warning: 10
  error: 20

# SwiftUI специфичные настройки
closure_body_length:
  warning: 30
  error: 50

# Настройки для многострочных выражений
multiline_arguments:
  first_argument_location: next_line
  only_enforce_after_first_closure_on_first_line: true

multiline_parameters:
  allows_single_line: true

# Настройки для вертикальных отступов
vertical_whitespace:
  max_empty_lines: 2

# Настройки для trailing closure
trailing_closure:
  only_single_muted_parameter: true

# Настройки для force unwrapping (строгие для безопасности)
force_unwrapping:
  severity: error

# Настройки для implicit return (SwiftUI стиль)
implicit_return:
  included:
    - closure
    - function
    - getter

# Пользовательские правила
custom_rules:
  # Правило для использования @Published в ViewModel
  published_property:
    name: "Published Property"
    regex: '@Published\s+private\s+'
    message: "@Published properties should not be private"
    severity: warning

  # Правило для правильного именования SwiftUI Views
  swiftui_view_naming:
    name: "SwiftUI View Naming"
    regex: 'struct\s+\w+(?<!View):\s+View'
    message: "SwiftUI Views should end with 'View'"
    severity: warning

  # Правило для использования Logger вместо print
  no_print_statements:
    name: "No Print Statements"
    regex: '\bprint\s*\('
    message: "Use Logger instead of print for debugging"
    severity: warning

  # Правило для TODO комментариев
  todo_comments:
    name: "TODO Comments"
    regex: '(TODO|FIXME|HACK)'
    message: "TODO/FIXME/HACK comments should be resolved"
    severity: warning

reporter: "xcode" # Использовать Xcode reporter для лучшей интеграции 