name: 🐛 Bug Report
description: Сообщить об ошибке в приложении
title: "[BUG]: "
labels: ["bug", "needs-triage"]
assignees: []

body:
  - type: markdown
    attributes:
      value: |
        Спасибо за сообщение об ошибке! Пожалуйста, заполните форму максимально подробно.

  - type: textarea
    id: description
    attributes:
      label: 📝 Описание ошибки
      description: Кратко опишите, что произошло
      placeholder: Опишите проблему...
    validations:
      required: true

  - type: textarea
    id: reproduction
    attributes:
      label: 🔄 Шаги для воспроизведения
      description: Опишите, как воспроизвести ошибку
      placeholder: |
        1. Открыть экран '...'
        2. Нажать на '...'
        3. Прокрутить до '...'
        4. Увидеть ошибку
    validations:
      required: true

  - type: textarea
    id: expected
    attributes:
      label: ✅ Ожидаемое поведение
      description: Что должно было произойти?
      placeholder: Опишите ожидаемое поведение...
    validations:
      required: true

  - type: textarea
    id: actual
    attributes:
      label: ❌ Фактическое поведение
      description: Что произошло на самом деле?
      placeholder: Опишите фактическое поведение...
    validations:
      required: true

  - type: dropdown
    id: platform
    attributes:
      label: 📱 Платформа
      description: На какой платформе возникла ошибка?
      options:
        - iOS
        - macOS
        - Обе платформы
    validations:
      required: true

  - type: input
    id: device
    attributes:
      label: 📱 Устройство
      description: Какое устройство использовалось?
      placeholder: "iPhone 15 Pro, MacBook Pro M2, etc."
    validations:
      required: true

  - type: input
    id: ios-version
    attributes:
      label: 🔢 Версия ОС
      description: Какая версия iOS/macOS?
      placeholder: "iOS 17.2, macOS 14.1, etc."
    validations:
      required: true

  - type: input
    id: app-version
    attributes:
      label: 📦 Версия приложения
      description: Какая версия приложения?
      placeholder: "1.0.0 (1)"
    validations:
      required: true

  - type: textarea
    id: logs
    attributes:
      label: 📋 Логи/Скриншоты
      description: Добавьте логи, скриншоты или другую полезную информацию
      placeholder: |
        Приложите:
        - Скриншоты ошибки
        - Crash logs
        - Console output
        - Другая полезная информация

  - type: dropdown
    id: frequency
    attributes:
      label: 🔄 Частота воспроизведения
      description: Как часто возникает эта ошибка?
      options:
        - Всегда (100%)
        - Часто (75-99%)
        - Иногда (25-74%)
        - Редко (1-24%)
        - Только один раз
    validations:
      required: true

  - type: dropdown
    id: severity
    attributes:
      label: ⚠️ Серьезность
      description: Насколько серьезна эта ошибка?
      options:
        - Критическая (приложение крашится)
        - Высокая (основная функция не работает)
        - Средняя (мешает использованию)
        - Низкая (незначительная проблема)
    validations:
      required: true

  - type: checkboxes
    id: checks
    attributes:
      label: ✅ Checklist
      description: Пожалуйста, подтвердите
      options:
        - label: Я обновил приложение до последней версии
          required: false
        - label: Я проверил, что такой issue еще не создан
          required: true
        - label: Я следовал шаблону отчета об ошибке
          required: true 