name: ✨ Feature Request
description: Предложить новую функциональность
title: "[FEATURE]: "
labels: ["enhancement", "needs-discussion"]
assignees: []

body:
  - type: markdown
    attributes:
      value: |
        Спасибо за предложение новой функциональности! Расскажите нам подробнее.

  - type: textarea
    id: problem
    attributes:
      label: 🎯 Проблема
      description: Какую проблему решает предлагаемая функция?
      placeholder: |
        Опишите проблему, которую пытаетесь решить...
        Например: "Трудно отслеживать прогресс привычек на неделю"
    validations:
      required: true

  - type: textarea
    id: solution
    attributes:
      label: 💡 Предлагаемое решение
      description: Опишите, как должна работать новая функция
      placeholder: |
        Детально опишите предлагаемое решение...
        Включите UI/UX описание, пользовательские сценарии, etc.
    validations:
      required: true

  - type: textarea
    id: alternatives
    attributes:
      label: 🔄 Альтернативные решения
      description: Рассматривали ли вы другие способы решения проблемы?
      placeholder: Опишите альтернативные подходы...
    validations:
      required: false

  - type: dropdown
    id: feature-type
    attributes:
      label: 📂 Тип функциональности
      description: К какой области относится предложение?
      options:
        - Привычки (Habits)
        - Задачи (Tasks)
        - Цели (Goals)
        - Финансы (Finance)
        - Геймификация (Gamification)
        - UI/UX
        - Настройки
        - Интеграции
        - Производительность
        - Безопасность
        - Другое
    validations:
      required: true

  - type: dropdown
    id: priority
    attributes:
      label: ⚡ Приоритет
      description: Насколько важна эта функция?
      options:
        - Критический (блокирует использование)
        - Высокий (значительно улучшит UX)
        - Средний (полезное улучшение)
        - Низкий (nice to have)
    validations:
      required: true

  - type: dropdown
    id: platform
    attributes:
      label: 📱 Платформа
      description: Для какой платформы предназначена функция?
      options:
        - iOS
        - macOS
        - Обе платформы
        - Widget
        - Apple Watch (будущее)
    validations:
      required: true

  - type: textarea
    id: user-stories
    attributes:
      label: 👤 Пользовательские сценарии
      description: Опишите, как пользователи будут взаимодействовать с функцией
      placeholder: |
        Как [тип пользователя], я хочу [действие], чтобы [результат]
        
        Например:
        - Как активный пользователь, я хочу видеть еженедельную статистику, чтобы отслеживать прогресс
        - Как новичок, я хочу получать советы по формированию привычек, чтобы быстрее достичь целей
    validations:
      required: false

  - type: textarea
    id: mockups
    attributes:
      label: 🎨 Макеты/Скриншоты
      description: Добавьте макеты, скетчи или примеры из других приложений
      placeholder: |
        Прикрепите:
        - Скетчи интерфейса
        - Макеты дизайна
        - Примеры из других приложений
        - Схемы взаимодействия

  - type: textarea
    id: technical-notes
    attributes:
      label: 🔧 Технические заметки
      description: Есть ли технические требования или ограничения?
      placeholder: |
        Например:
        - Требует интеграции с HealthKit
        - Нужна поддержка CloudKit sync
        - Потребует изменения модели данных
    validations:
      required: false

  - type: dropdown
    id: complexity
    attributes:
      label: 🎯 Сложность реализации
      description: Как вы оцениваете сложность?
      options:
        - Простая (несколько часов)
        - Средняя (несколько дней)
        - Сложная (несколько недель)
        - Очень сложная (требует исследования)
        - Не знаю
    validations:
      required: false

  - type: checkboxes
    id: checks
    attributes:
      label: ✅ Checklist
      description: Пожалуйста, подтвердите
      options:
        - label: Я проверил, что такое предложение еще не создано
          required: true
        - label: Я подумал об альтернативных решениях
          required: true
        - label: Функция соответствует концепции приложения
          required: true
        - label: Я готов участвовать в обсуждении реализации
          required: false 