name: Setup Branch Protection

on:
  workflow_dispatch: # Ручной запуск
  
jobs:
  setup-protection:
    name: Setup Branch Protection Rules
    runs-on: ubuntu-latest
    if: github.actor == github.repository_owner
    
    steps:
      - name: Setup Branch Protection for main
        uses: actions/github-script@v7
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            try {
              await github.rest.repos.updateBranchProtection({
                owner: context.repo.owner,
                repo: context.repo.repo,
                branch: 'main',
                required_status_checks: {
                  strict: true,
                  contexts: [
                    'SwiftLint',
                    'Build & Test iOS',
                    'Build & Test macOS',
                    'Security & Quality Scan'
                  ]
                },
                enforce_admins: false,
                required_pull_request_reviews: {
                  required_approving_review_count: 1,
                  dismiss_stale_reviews: true,
                  require_code_owner_reviews: false,
                  require_last_push_approval: false
                },
                restrictions: null,
                allow_force_pushes: false,
                allow_deletions: false,
                block_creations: false,
                required_conversation_resolution: true
              });
              
              console.log('✅ Branch protection rules установлены для main');
            } catch (error) {
              console.log('❌ Ошибка установки branch protection:', error.message);
            }

      - name: Setup Branch Protection for develop
        uses: actions/github-script@v7
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            try {
              await github.rest.repos.updateBranchProtection({
                owner: context.repo.owner,
                repo: context.repo.repo,
                branch: 'develop',
                required_status_checks: {
                  strict: true,
                  contexts: [
                    'SwiftLint',
                    'Build & Test iOS',
                    'Build & Test macOS'
                  ]
                },
                enforce_admins: false,
                required_pull_request_reviews: {
                  required_approving_review_count: 1,
                  dismiss_stale_reviews: true,
                  require_code_owner_reviews: false,
                  require_last_push_approval: false
                },
                restrictions: null,
                allow_force_pushes: false,
                allow_deletions: false,
                block_creations: false,
                required_conversation_resolution: true
              });
              
              console.log('✅ Branch protection rules установлены для develop');
            } catch (error) {
              console.log('❌ Ошибка установки branch protection:', error.message);
            } 